# Generated by Django 3.0.3 on 2020-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='LinkedIn',
            field=models.URLField(default='null'),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default=False, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default=False, max_length=60),
        ),
    ]
