# Generated by Django 3.0.3 on 2020-05-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200530_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='e_field',
            field=models.EmailField(default=False, max_length=254, unique=True),
        ),
    ]
