# Generated by Django 3.0.3 on 2020-06-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200531_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='e_field',
        ),
    ]
