# Generated by Django 3.0.3 on 2020-06-05 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang_approved',
            field=models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English'), ('french', 'French')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2020, max_length=4),
        ),
    ]
