# Generated by Django 3.0.3 on 2020-06-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200605_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='color',
        ),
    ]
