# Generated by Django 3.0.3 on 2020-06-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200605_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Subject'),
        ),
    ]
